#Obstacle marking parameters
obstacle_range: 3.5
max_obstacle_height: 5.0
raytrace_range: 5.0

#Robot's footprint
footprint: [[-1.18, 0.6], [-1.18, -0.6], [1.25, -0.6],[1.25, 0.6]]

#Cost function parameters
inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
